costmap_3d:
  ang_resolution: 16
  linear_expand: 0.08
  linear_spread: 0.3
  static_layers: # static_layers: all cells in the costmap are updated at once (usually for global map)
    - name: unknown
      type: Costmap3dLayerUnknownHandle # Set unknown cell's cost.
      unknown_cost: 100
      overlay_mode: max
    - name: overlay0
      type: Costmap3dLayerPlain # Costmap layer without considering footprint.
      overlay_mode: max
      linear_expand: 0.0
      linear_spread: 0.0
  layers: # layers: the costmap can be partially (usually for local map)
    - name: stop_propagation
      type: Costmap3dLayerStopPropagation # Stop propagating parent layer's cost to the child. This can be used at the beginning of layer to ignore changes in static layers.
      overlay_mode: max
    - name: overlay2
      type: Costmap3dLayerFootprint # Configuration space costmap layer according to the given footprint.
      overlay_mode: max
      linear_expand: 0.08
      linear_spread: 0.0
      keep_unknown: true
    - name: overlay1
      type: Costmap3dLayerFootprint # Configuration space costmap layer according to the given footprint.
      overlay_mode: max
      linear_expand: 0.15
      linear_spread: 0.3
      keep_unknown: true
planner_3d:
  num_threads: 2
  freq: 2.0
  freq_min: 0.5
  local_range: 2.0
  remember_updates: true
  hist_ignore_range: 0.0
  hist_ignore_range_max: 1.5
spur:
  hz: 30.0
  k_dist: 16.0
  k_ang: 10.0
  k_avel: 4.0
  dist_lim: 0.5
  goal_tolerance_dist: 0.05
  goal_tolerance_ang: 0.05
  stop_tolerance_dist: 0.04
  stop_tolerance_ang: 0.04
  no_position_control_dist: 0.05
  limit_vel_by_avel: true
  path_step: 1
  look_forward: 0.0
  curv_forward: 0.5